// Configuration des achievements - 100 achievements au total
import { Achievement, AchievementRarity } from '../types';

// Re-export for convenience
export type { AchievementRarity } from '../types';

export const ACHIEVEMENT_CATEGORIES = [
  { id: 'tasks', name: 'Tâches', icon: '📝' },
  { id: 'streaks', name: 'Séries', icon: '🔥' },
  { id: 'quests', name: 'Quêtes', icon: '🎯' },
  { id: 'xp', name: 'Expérience', icon: '✨' },
  { id: 'time', name: 'Temps', icon: '⏰' },
  { id: 'categories', name: 'Catégories', icon: '📂' },
  { id: 'collection', name: 'Collection', icon: '🏆' },
  { id: 'special', name: 'Spécial', icon: '⭐' },
];

export const ACHIEVEMENTS: Omit<Achievement, 'unlockedAt'>[] = [
  // ============================================
  // TASKS - Tâches complétées (15 achievements)
  // ============================================
  {
    id: 'first_task',
    name: 'Premier Pas',
    description: 'Complétez votre première tâche',
    icon: '🎯',
    rarity: 'common',
    category: 'tasks',
    xpReward: 10,
    coinReward: 5,
    requirement: { type: 'tasks_completed', value: 1 },
  },
  {
    id: 'task_5',
    name: 'Échauffement',
    description: 'Complétez 5 tâches',
    icon: '🏃',
    rarity: 'common',
    category: 'tasks',
    xpReward: 15,
    coinReward: 8,
    requirement: { type: 'tasks_completed', value: 5 },
  },
  {
    id: 'task_10',
    name: 'Débutant',
    description: 'Complétez 10 tâches',
    icon: '📝',
    rarity: 'common',
    category: 'tasks',
    xpReward: 25,
    coinReward: 10,
    requirement: { type: 'tasks_completed', value: 10 },
  },
  {
    id: 'task_25',
    name: 'En Route',
    description: 'Complétez 25 tâches',
    icon: '🚶',
    rarity: 'common',
    category: 'tasks',
    xpReward: 50,
    coinReward: 25,
    requirement: { type: 'tasks_completed', value: 25 },
  },
  {
    id: 'task_50',
    name: 'Travailleur',
    description: 'Complétez 50 tâches',
    icon: '💼',
    rarity: 'rare',
    category: 'tasks',
    xpReward: 100,
    coinReward: 50,
    requirement: { type: 'tasks_completed', value: 50 },
  },
  {
    id: 'task_100',
    name: 'Productif',
    description: 'Complétez 100 tâches',
    icon: '🏆',
    rarity: 'rare',
    category: 'tasks',
    xpReward: 200,
    coinReward: 100,
    requirement: { type: 'tasks_completed', value: 100 },
  },
  {
    id: 'task_250',
    name: 'Infatigable',
    description: 'Complétez 250 tâches',
    icon: '💪',
    rarity: 'rare',
    category: 'tasks',
    xpReward: 350,
    coinReward: 175,
    requirement: { type: 'tasks_completed', value: 250 },
  },
  {
    id: 'task_500',
    name: 'Machine de Guerre',
    description: 'Complétez 500 tâches',
    icon: '⚔️',
    rarity: 'epic',
    category: 'tasks',
    xpReward: 500,
    coinReward: 250,
    requirement: { type: 'tasks_completed', value: 500 },
  },
  {
    id: 'task_750',
    name: 'Force de la Nature',
    description: 'Complétez 750 tâches',
    icon: '🌪️',
    rarity: 'epic',
    category: 'tasks',
    xpReward: 750,
    coinReward: 375,
    requirement: { type: 'tasks_completed', value: 750 },
  },
  {
    id: 'task_1000',
    name: 'Légende Vivante',
    description: 'Complétez 1000 tâches',
    icon: '👑',
    rarity: 'legendary',
    category: 'tasks',
    xpReward: 1000,
    coinReward: 500,
    requirement: { type: 'tasks_completed', value: 1000 },
  },
  {
    id: 'task_2500',
    name: 'Transcendance',
    description: 'Complétez 2500 tâches',
    icon: '🌟',
    rarity: 'legendary',
    category: 'tasks',
    xpReward: 2500,
    coinReward: 1250,
    requirement: { type: 'tasks_completed', value: 2500 },
  },
  {
    id: 'task_5000',
    name: 'Divinité',
    description: 'Complétez 5000 tâches',
    icon: '🔱',
    rarity: 'legendary',
    category: 'tasks',
    xpReward: 5000,
    coinReward: 2500,
    requirement: { type: 'tasks_completed', value: 5000 },
    secret: true,
  },

  // ============================================
  // TASK DIFFICULTY - Tâches par difficulté (10 achievements)
  // ============================================
  {
    id: 'first_epic',
    name: 'Premier Défi Épique',
    description: 'Complétez une tâche épique',
    icon: '💜',
    rarity: 'rare',
    category: 'tasks',
    xpReward: 100,
    coinReward: 50,
    requirement: { type: 'epic_tasks', value: 1 },
  },
  {
    id: 'epic_10',
    name: 'Chasseur d\'Épiques',
    description: 'Complétez 10 tâches épiques',
    icon: '🎆',
    rarity: 'rare',
    category: 'tasks',
    xpReward: 200,
    coinReward: 100,
    requirement: { type: 'epic_tasks', value: 10 },
  },
  {
    id: 'epic_50',
    name: 'Maître Épique',
    description: 'Complétez 50 tâches épiques',
    icon: '🔮',
    rarity: 'epic',
    category: 'tasks',
    xpReward: 500,
    coinReward: 250,
    requirement: { type: 'epic_tasks', value: 50 },
  },
  {
    id: 'first_legendary',
    name: 'Légende',
    description: 'Complétez une tâche légendaire',
    icon: '🌟',
    rarity: 'epic',
    category: 'tasks',
    xpReward: 250,
    coinReward: 125,
    requirement: { type: 'legendary_tasks', value: 1 },
  },
  {
    id: 'legendary_10',
    name: 'Chasseur de Légendes',
    description: 'Complétez 10 tâches légendaires',
    icon: '⭐',
    rarity: 'epic',
    category: 'tasks',
    xpReward: 500,
    coinReward: 250,
    requirement: { type: 'legendary_tasks', value: 10 },
  },
  {
    id: 'legendary_25',
    name: 'Forgeur de Légendes',
    description: 'Complétez 25 tâches légendaires',
    icon: '🏅',
    rarity: 'legendary',
    category: 'tasks',
    xpReward: 1000,
    coinReward: 500,
    requirement: { type: 'legendary_tasks', value: 25 },
  },
  {
    id: 'legendary_50',
    name: 'Mythe Vivant',
    description: 'Complétez 50 tâches légendaires',
    icon: '👑',
    rarity: 'legendary',
    category: 'tasks',
    xpReward: 2000,
    coinReward: 1000,
    requirement: { type: 'legendary_tasks', value: 50 },
    secret: true,
  },
  {
    id: 'hard_tasks_10',
    name: 'Défi Relevé',
    description: 'Complétez 10 tâches difficiles ou plus',
    icon: '💪',
    rarity: 'rare',
    category: 'tasks',
    xpReward: 150,
    coinReward: 75,
    requirement: { type: 'hard_tasks', value: 10 },
  },
  {
    id: 'hard_tasks_50',
    name: 'Inébranlable',
    description: 'Complétez 50 tâches difficiles ou plus',
    icon: '🗿',
    rarity: 'epic',
    category: 'tasks',
    xpReward: 400,
    coinReward: 200,
    requirement: { type: 'hard_tasks', value: 50 },
  },
  {
    id: 'high_priority_25',
    name: 'Prioritaire',
    description: 'Complétez 25 tâches haute priorité',
    icon: '🔴',
    rarity: 'rare',
    category: 'tasks',
    xpReward: 200,
    coinReward: 100,
    requirement: { type: 'high_priority_tasks', value: 25 },
  },

  // ============================================
  // STREAKS - Séries (12 achievements)
  // ============================================
  {
    id: 'streak_3',
    name: 'Régularité',
    description: 'Maintenez un streak de 3 jours',
    icon: '🔥',
    rarity: 'common',
    category: 'streaks',
    xpReward: 30,
    coinReward: 15,
    requirement: { type: 'streak', value: 3 },
  },
  {
    id: 'streak_7',
    name: 'Semaine Parfaite',
    description: 'Maintenez un streak de 7 jours',
    icon: '📅',
    rarity: 'common',
    category: 'streaks',
    xpReward: 75,
    coinReward: 35,
    requirement: { type: 'streak', value: 7 },
  },
  {
    id: 'streak_14',
    name: 'Persévérant',
    description: 'Maintenez un streak de 14 jours',
    icon: '💪',
    rarity: 'rare',
    category: 'streaks',
    xpReward: 150,
    coinReward: 75,
    requirement: { type: 'streak', value: 14 },
  },
  {
    id: 'streak_21',
    name: 'Trois Semaines',
    description: 'Maintenez un streak de 21 jours',
    icon: '🌙',
    rarity: 'rare',
    category: 'streaks',
    xpReward: 200,
    coinReward: 100,
    requirement: { type: 'streak', value: 21 },
  },
  {
    id: 'streak_30',
    name: 'Mois Légendaire',
    description: 'Maintenez un streak de 30 jours',
    icon: '🌟',
    rarity: 'epic',
    category: 'streaks',
    xpReward: 300,
    coinReward: 150,
    requirement: { type: 'streak', value: 30 },
  },
  {
    id: 'streak_60',
    name: 'Deux Mois',
    description: 'Maintenez un streak de 60 jours',
    icon: '🎖️',
    rarity: 'epic',
    category: 'streaks',
    xpReward: 600,
    coinReward: 300,
    requirement: { type: 'streak', value: 60 },
  },
  {
    id: 'streak_90',
    name: 'Trimestre Parfait',
    description: 'Maintenez un streak de 90 jours',
    icon: '🏆',
    rarity: 'epic',
    category: 'streaks',
    xpReward: 900,
    coinReward: 450,
    requirement: { type: 'streak', value: 90 },
  },
  {
    id: 'streak_100',
    name: 'Centurion',
    description: 'Maintenez un streak de 100 jours',
    icon: '🏛️',
    rarity: 'legendary',
    category: 'streaks',
    xpReward: 1000,
    coinReward: 500,
    requirement: { type: 'streak', value: 100 },
  },
  {
    id: 'streak_180',
    name: 'Demi-Année',
    description: 'Maintenez un streak de 180 jours',
    icon: '🌓',
    rarity: 'legendary',
    category: 'streaks',
    xpReward: 1800,
    coinReward: 900,
    requirement: { type: 'streak', value: 180 },
  },
  {
    id: 'streak_365',
    name: 'Année Incroyable',
    description: 'Maintenez un streak de 365 jours',
    icon: '🎆',
    rarity: 'legendary',
    category: 'streaks',
    xpReward: 5000,
    coinReward: 2500,
    requirement: { type: 'streak', value: 365 },
    secret: true,
  },
  {
    id: 'streak_500',
    name: 'Immortel',
    description: 'Maintenez un streak de 500 jours',
    icon: '♾️',
    rarity: 'legendary',
    category: 'streaks',
    xpReward: 7500,
    coinReward: 3750,
    requirement: { type: 'streak', value: 500 },
    secret: true,
  },
  {
    id: 'streak_1000',
    name: 'Éternel',
    description: 'Maintenez un streak de 1000 jours',
    icon: '🌌',
    rarity: 'legendary',
    category: 'streaks',
    xpReward: 15000,
    coinReward: 7500,
    requirement: { type: 'streak', value: 1000 },
    secret: true,
  },

  // ============================================
  // LEVELS - Niveaux (12 achievements)
  // ============================================
  {
    id: 'level_5',
    name: 'Apprenti',
    description: 'Atteignez le niveau 5',
    icon: '📈',
    rarity: 'common',
    category: 'xp',
    xpReward: 50,
    coinReward: 25,
    requirement: { type: 'level', value: 5 },
  },
  {
    id: 'level_10',
    name: 'Aventurier',
    description: 'Atteignez le niveau 10',
    icon: '🗺️',
    rarity: 'common',
    category: 'xp',
    xpReward: 100,
    coinReward: 50,
    requirement: { type: 'level', value: 10 },
  },
  {
    id: 'level_15',
    name: 'Explorateur',
    description: 'Atteignez le niveau 15',
    icon: '🧭',
    rarity: 'common',
    category: 'xp',
    xpReward: 150,
    coinReward: 75,
    requirement: { type: 'level', value: 15 },
  },
  {
    id: 'level_20',
    name: 'Vétéran',
    description: 'Atteignez le niveau 20',
    icon: '🎖️',
    rarity: 'rare',
    category: 'xp',
    xpReward: 200,
    coinReward: 100,
    requirement: { type: 'level', value: 20 },
  },
  {
    id: 'level_25',
    name: 'Héros',
    description: 'Atteignez le niveau 25',
    icon: '🦸',
    rarity: 'rare',
    category: 'xp',
    xpReward: 250,
    coinReward: 125,
    requirement: { type: 'level', value: 25 },
  },
  {
    id: 'level_30',
    name: 'Élite',
    description: 'Atteignez le niveau 30',
    icon: '⚡',
    rarity: 'rare',
    category: 'xp',
    xpReward: 300,
    coinReward: 150,
    requirement: { type: 'level', value: 30 },
  },
  {
    id: 'level_40',
    name: 'Guerrier',
    description: 'Atteignez le niveau 40',
    icon: '⚔️',
    rarity: 'epic',
    category: 'xp',
    xpReward: 400,
    coinReward: 200,
    requirement: { type: 'level', value: 40 },
  },
  {
    id: 'level_50',
    name: 'Champion',
    description: 'Atteignez le niveau 50',
    icon: '🏅',
    rarity: 'epic',
    category: 'xp',
    xpReward: 500,
    coinReward: 250,
    requirement: { type: 'level', value: 50 },
  },
  {
    id: 'level_75',
    name: 'Grand Maître',
    description: 'Atteignez le niveau 75',
    icon: '🎓',
    rarity: 'epic',
    category: 'xp',
    xpReward: 750,
    coinReward: 375,
    requirement: { type: 'level', value: 75 },
  },
  {
    id: 'level_100',
    name: 'Maître Légendaire',
    description: 'Atteignez le niveau 100',
    icon: '👑',
    rarity: 'legendary',
    category: 'xp',
    xpReward: 2000,
    coinReward: 1000,
    requirement: { type: 'level', value: 100 },
  },
  {
    id: 'level_150',
    name: 'Titan',
    description: 'Atteignez le niveau 150',
    icon: '🗿',
    rarity: 'legendary',
    category: 'xp',
    xpReward: 3000,
    coinReward: 1500,
    requirement: { type: 'level', value: 150 },
    secret: true,
  },
  {
    id: 'level_200',
    name: 'Dieu',
    description: 'Atteignez le niveau 200',
    icon: '🔱',
    rarity: 'legendary',
    category: 'xp',
    xpReward: 5000,
    coinReward: 2500,
    requirement: { type: 'level', value: 200 },
    secret: true,
  },

  // ============================================
  // XP MILESTONES - Jalons d'XP (8 achievements)
  // ============================================
  {
    id: 'xp_500',
    name: 'Premiers Gains',
    description: 'Gagnez 500 XP au total',
    icon: '✨',
    rarity: 'common',
    category: 'xp',
    xpReward: 25,
    coinReward: 12,
    requirement: { type: 'total_xp', value: 500 },
  },
  {
    id: 'xp_1000',
    name: 'Collectionneur d\'XP',
    description: 'Gagnez 1000 XP au total',
    icon: '💫',
    rarity: 'common',
    category: 'xp',
    xpReward: 50,
    coinReward: 25,
    requirement: { type: 'total_xp', value: 1000 },
  },
  {
    id: 'xp_5000',
    name: 'Accumulateur',
    description: 'Gagnez 5000 XP au total',
    icon: '🌠',
    rarity: 'rare',
    category: 'xp',
    xpReward: 150,
    coinReward: 75,
    requirement: { type: 'total_xp', value: 5000 },
  },
  {
    id: 'xp_10000',
    name: 'Chasseur d\'XP',
    description: 'Gagnez 10000 XP au total',
    icon: '🎇',
    rarity: 'rare',
    category: 'xp',
    xpReward: 200,
    coinReward: 100,
    requirement: { type: 'total_xp', value: 10000 },
  },
  {
    id: 'xp_25000',
    name: 'Amasseur',
    description: 'Gagnez 25000 XP au total',
    icon: '💰',
    rarity: 'epic',
    category: 'xp',
    xpReward: 400,
    coinReward: 200,
    requirement: { type: 'total_xp', value: 25000 },
  },
  {
    id: 'xp_50000',
    name: 'Baron de l\'XP',
    description: 'Gagnez 50000 XP au total',
    icon: '👔',
    rarity: 'epic',
    category: 'xp',
    xpReward: 750,
    coinReward: 375,
    requirement: { type: 'total_xp', value: 50000 },
  },
  {
    id: 'xp_100000',
    name: 'Maître de l\'XP',
    description: 'Gagnez 100000 XP au total',
    icon: '🌌',
    rarity: 'legendary',
    category: 'xp',
    xpReward: 1000,
    coinReward: 500,
    requirement: { type: 'total_xp', value: 100000 },
  },
  {
    id: 'xp_250000',
    name: 'Légende de l\'XP',
    description: 'Gagnez 250000 XP au total',
    icon: '🌟',
    rarity: 'legendary',
    category: 'xp',
    xpReward: 2500,
    coinReward: 1250,
    requirement: { type: 'total_xp', value: 250000 },
    secret: true,
  },

  // ============================================
  // TIME MANAGEMENT - Gestion du temps (10 achievements)
  // ============================================
  {
    id: 'early_bird',
    name: 'Lève-tôt',
    description: 'Complétez une tâche avant 7h du matin',
    icon: '🌅',
    rarity: 'common',
    category: 'time',
    xpReward: 25,
    coinReward: 10,
    requirement: { type: 'early_completion', value: 1 },
  },
  {
    id: 'early_bird_10',
    name: 'Matinal',
    description: 'Complétez 10 tâches avant 7h du matin',
    icon: '☀️',
    rarity: 'rare',
    category: 'time',
    xpReward: 100,
    coinReward: 50,
    requirement: { type: 'early_completion', value: 10 },
  },
  {
    id: 'early_bird_50',
    name: 'Maître de l\'Aube',
    description: 'Complétez 50 tâches avant 7h du matin',
    icon: '🌄',
    rarity: 'epic',
    category: 'time',
    xpReward: 300,
    coinReward: 150,
    requirement: { type: 'early_completion', value: 50 },
  },
  {
    id: 'night_owl',
    name: 'Oiseau de Nuit',
    description: 'Complétez une tâche après minuit',
    icon: '🦉',
    rarity: 'common',
    category: 'time',
    xpReward: 25,
    coinReward: 10,
    requirement: { type: 'late_completion', value: 1 },
  },
  {
    id: 'night_owl_10',
    name: 'Noctambule',
    description: 'Complétez 10 tâches après minuit',
    icon: '🌙',
    rarity: 'rare',
    category: 'time',
    xpReward: 100,
    coinReward: 50,
    requirement: { type: 'late_completion', value: 10 },
  },
  {
    id: 'night_owl_50',
    name: 'Seigneur de la Nuit',
    description: 'Complétez 50 tâches après minuit',
    icon: '🌑',
    rarity: 'epic',
    category: 'time',
    xpReward: 300,
    coinReward: 150,
    requirement: { type: 'late_completion', value: 50 },
  },
  {
    id: 'perfect_day',
    name: 'Journée Parfaite',
    description: 'Complétez toutes vos tâches du jour (min 3)',
    icon: '☀️',
    rarity: 'rare',
    category: 'time',
    xpReward: 100,
    coinReward: 50,
    requirement: { type: 'perfect_day', value: 1 },
  },
  {
    id: 'perfect_day_7',
    name: 'Semaine Parfaite',
    description: 'Ayez 7 journées parfaites',
    icon: '🌈',
    rarity: 'epic',
    category: 'time',
    xpReward: 500,
    coinReward: 250,
    requirement: { type: 'perfect_day', value: 7 },
  },
  {
    id: 'perfect_day_30',
    name: 'Mois Parfait',
    description: 'Ayez 30 journées parfaites',
    icon: '🏆',
    rarity: 'legendary',
    category: 'time',
    xpReward: 1500,
    coinReward: 750,
    requirement: { type: 'perfect_day', value: 30 },
  },
  {
    id: 'weekend_warrior',
    name: 'Guerrier du Weekend',
    description: 'Complétez 10 tâches le weekend',
    icon: '🎉',
    rarity: 'rare',
    category: 'time',
    xpReward: 100,
    coinReward: 50,
    requirement: { type: 'weekend_tasks', value: 10 },
  },

  // ============================================
  // DAILY XP - XP quotidien (6 achievements)
  // ============================================
  {
    id: 'daily_xp_100',
    name: 'Journée Active',
    description: 'Gagnez 100 XP en une journée',
    icon: '⚡',
    rarity: 'common',
    category: 'xp',
    xpReward: 25,
    coinReward: 12,
    requirement: { type: 'daily_xp', value: 100 },
  },
  {
    id: 'daily_xp_250',
    name: 'Journée Productive',
    description: 'Gagnez 250 XP en une journée',
    icon: '🔥',
    rarity: 'rare',
    category: 'xp',
    xpReward: 75,
    coinReward: 35,
    requirement: { type: 'daily_xp', value: 250 },
  },
  {
    id: 'daily_xp_500',
    name: 'Surpassement',
    description: 'Gagnez 500 XP en une journée',
    icon: '🚀',
    rarity: 'epic',
    category: 'xp',
    xpReward: 250,
    coinReward: 125,
    requirement: { type: 'daily_xp', value: 500 },
  },
  {
    id: 'daily_xp_1000',
    name: 'Jour de Gloire',
    description: 'Gagnez 1000 XP en une journée',
    icon: '👑',
    rarity: 'legendary',
    category: 'xp',
    xpReward: 500,
    coinReward: 250,
    requirement: { type: 'daily_xp', value: 1000 },
  },
  {
    id: 'daily_tasks_5',
    name: 'Quinté',
    description: 'Complétez 5 tâches en une journée',
    icon: '🎯',
    rarity: 'common',
    category: 'tasks',
    xpReward: 50,
    coinReward: 25,
    requirement: { type: 'daily_tasks', value: 5 },
  },
  {
    id: 'daily_tasks_10',
    name: 'Décathlon',
    description: 'Complétez 10 tâches en une journée',
    icon: '🏃',
    rarity: 'rare',
    category: 'tasks',
    xpReward: 150,
    coinReward: 75,
    requirement: { type: 'daily_tasks', value: 10 },
  },

  // ============================================
  // CATEGORIES - Catégories (8 achievements)
  // ============================================
  {
    id: 'category_first',
    name: 'Premier Spécialiste',
    description: 'Complétez 10 tâches dans une catégorie',
    icon: '📁',
    rarity: 'common',
    category: 'categories',
    xpReward: 50,
    coinReward: 25,
    requirement: { type: 'category_tasks', value: 10 },
  },
  {
    id: 'category_25',
    name: 'Expert',
    description: 'Complétez 25 tâches dans une catégorie',
    icon: '📚',
    rarity: 'rare',
    category: 'categories',
    xpReward: 100,
    coinReward: 50,
    requirement: { type: 'category_tasks', value: 25 },
  },
  {
    id: 'category_master',
    name: 'Spécialiste',
    description: 'Complétez 50 tâches dans une catégorie',
    icon: '🎓',
    rarity: 'rare',
    category: 'categories',
    xpReward: 150,
    coinReward: 75,
    requirement: { type: 'category_tasks', value: 50 },
  },
  {
    id: 'category_100',
    name: 'Grand Spécialiste',
    description: 'Complétez 100 tâches dans une catégorie',
    icon: '🏆',
    rarity: 'epic',
    category: 'categories',
    xpReward: 300,
    coinReward: 150,
    requirement: { type: 'category_tasks', value: 100 },
  },
  {
    id: 'category_legend',
    name: 'Légende Catégorielle',
    description: 'Complétez 250 tâches dans une catégorie',
    icon: '👑',
    rarity: 'legendary',
    category: 'categories',
    xpReward: 750,
    coinReward: 375,
    requirement: { type: 'category_tasks', value: 250 },
  },
  {
    id: 'well_rounded',
    name: 'Polyvalent',
    description: 'Complétez au moins 1 tâche dans toutes les catégories',
    icon: '🌐',
    rarity: 'rare',
    category: 'categories',
    xpReward: 200,
    coinReward: 100,
    requirement: { type: 'all_categories', value: 1 },
  },
  {
    id: 'diversified',
    name: 'Diversifié',
    description: 'Complétez au moins 10 tâches dans toutes les catégories',
    icon: '🎨',
    rarity: 'epic',
    category: 'categories',
    xpReward: 400,
    coinReward: 200,
    requirement: { type: 'all_categories', value: 10 },
  },
  {
    id: 'jack_of_all',
    name: 'Touche-à-tout',
    description: 'Complétez au moins 25 tâches dans toutes les catégories',
    icon: '🎭',
    rarity: 'legendary',
    category: 'categories',
    xpReward: 1000,
    coinReward: 500,
    requirement: { type: 'all_categories', value: 25 },
  },

  // ============================================
  // QUESTS - Quêtes (10 achievements)
  // ============================================
  {
    id: 'quest_first',
    name: 'Quêteur',
    description: 'Complétez votre première quête',
    icon: '📜',
    rarity: 'common',
    category: 'quests',
    xpReward: 50,
    coinReward: 25,
    requirement: { type: 'quests_completed', value: 1 },
  },
  {
    id: 'quest_5',
    name: 'Aventurier',
    description: 'Complétez 5 quêtes',
    icon: '🗺️',
    rarity: 'common',
    category: 'quests',
    xpReward: 75,
    coinReward: 35,
    requirement: { type: 'quests_completed', value: 5 },
  },
  {
    id: 'quest_10',
    name: 'Aventurier Confirmé',
    description: 'Complétez 10 quêtes',
    icon: '🗡️',
    rarity: 'rare',
    category: 'quests',
    xpReward: 200,
    coinReward: 100,
    requirement: { type: 'quests_completed', value: 10 },
  },
  {
    id: 'quest_25',
    name: 'Héros des Quêtes',
    description: 'Complétez 25 quêtes',
    icon: '🛡️',
    rarity: 'rare',
    category: 'quests',
    xpReward: 350,
    coinReward: 175,
    requirement: { type: 'quests_completed', value: 25 },
  },
  {
    id: 'quest_50',
    name: 'Champion des Quêtes',
    description: 'Complétez 50 quêtes',
    icon: '⚔️',
    rarity: 'epic',
    category: 'quests',
    xpReward: 500,
    coinReward: 250,
    requirement: { type: 'quests_completed', value: 50 },
  },
  {
    id: 'quest_100',
    name: 'Légende des Quêtes',
    description: 'Complétez 100 quêtes',
    icon: '👑',
    rarity: 'legendary',
    category: 'quests',
    xpReward: 1000,
    coinReward: 500,
    requirement: { type: 'quests_completed', value: 100 },
  },
  {
    id: 'daily_quest_first',
    name: 'Routine Quotidienne',
    description: 'Complétez votre première quête journalière',
    icon: '📅',
    rarity: 'common',
    category: 'quests',
    xpReward: 25,
    coinReward: 12,
    requirement: { type: 'daily_quests', value: 1 },
  },
  {
    id: 'daily_quests_10',
    name: 'Habitué',
    description: 'Complétez 10 quêtes journalières',
    icon: '🔄',
    rarity: 'rare',
    category: 'quests',
    xpReward: 150,
    coinReward: 75,
    requirement: { type: 'daily_quests', value: 10 },
  },
  {
    id: 'daily_quests_30',
    name: 'Guerrier Quotidien',
    description: 'Complétez 30 quêtes journalières',
    icon: '⚔️',
    rarity: 'epic',
    category: 'quests',
    xpReward: 500,
    coinReward: 250,
    requirement: { type: 'daily_quests', value: 30 },
  },
  {
    id: 'daily_quests_100',
    name: 'Maître du Quotidien',
    description: 'Complétez 100 quêtes journalières',
    icon: '🏆',
    rarity: 'legendary',
    category: 'quests',
    xpReward: 1500,
    coinReward: 750,
    requirement: { type: 'daily_quests', value: 100 },
  },

  // ============================================
  // COLLECTION - Achievements d'achievements (5 achievements)
  // ============================================
  {
    id: 'collector_5',
    name: 'Débutant Collectionneur',
    description: 'Débloquez 5 achievements',
    icon: '📦',
    rarity: 'common',
    category: 'collection',
    xpReward: 50,
    coinReward: 25,
    requirement: { type: 'achievements', value: 5 },
  },
  {
    id: 'collector_10',
    name: 'Petit Collectionneur',
    description: 'Débloquez 10 achievements',
    icon: '🗃️',
    rarity: 'common',
    category: 'collection',
    xpReward: 100,
    coinReward: 50,
    requirement: { type: 'achievements', value: 10 },
  },
  {
    id: 'collector_25',
    name: 'Grand Collectionneur',
    description: 'Débloquez 25 achievements',
    icon: '📚',
    rarity: 'rare',
    category: 'collection',
    xpReward: 300,
    coinReward: 150,
    requirement: { type: 'achievements', value: 25 },
  },
  {
    id: 'collector_50',
    name: 'Maître Collectionneur',
    description: 'Débloquez 50 achievements',
    icon: '🏛️',
    rarity: 'epic',
    category: 'collection',
    xpReward: 600,
    coinReward: 300,
    requirement: { type: 'achievements', value: 50 },
  },
  {
    id: 'collector_all',
    name: 'Collectionneur Ultime',
    description: 'Débloquez tous les achievements non-secrets',
    icon: '🏆',
    rarity: 'legendary',
    category: 'collection',
    xpReward: 2000,
    coinReward: 1000,
    requirement: { type: 'achievements', value: 85 },
    secret: true,
  },

  // ============================================
  // SPECIAL - Achievements spéciaux (10 achievements)
  // ============================================
  {
    id: 'founder',
    name: 'Fondateur',
    description: 'Créez votre compte Questify',
    icon: '🏴',
    rarity: 'common',
    category: 'special',
    xpReward: 50,
    coinReward: 25,
    requirement: { type: 'account_created', value: 1 },
  },
  {
    id: 'comeback_7',
    name: 'Le Retour',
    description: 'Reconnectez-vous après 7 jours d\'absence',
    icon: '🔄',
    rarity: 'rare',
    category: 'special',
    xpReward: 75,
    coinReward: 35,
    requirement: { type: 'comeback', value: 7 },
    secret: true,
  },
  {
    id: 'comeback_30',
    name: 'Phoenix',
    description: 'Reconnectez-vous après 30 jours d\'absence',
    icon: '🔥',
    rarity: 'epic',
    category: 'special',
    xpReward: 150,
    coinReward: 75,
    requirement: { type: 'comeback', value: 30 },
    secret: true,
  },
  {
    id: 'perfectionist',
    name: 'Perfectionniste',
    description: 'Complétez 10 tâches avec toutes les sous-tâches',
    icon: '✅',
    rarity: 'rare',
    category: 'special',
    xpReward: 150,
    coinReward: 75,
    requirement: { type: 'perfect_tasks', value: 10 },
  },
  {
    id: 'perfectionist_50',
    name: 'Ultra Perfectionniste',
    description: 'Complétez 50 tâches avec toutes les sous-tâches',
    icon: '✨',
    rarity: 'epic',
    category: 'special',
    xpReward: 400,
    coinReward: 200,
    requirement: { type: 'perfect_tasks', value: 50 },
  },
  {
    id: 'coins_1000',
    name: 'Économe',
    description: 'Accumulez 1000 pièces',
    icon: '💰',
    rarity: 'rare',
    category: 'special',
    xpReward: 100,
    coinReward: 50,
    requirement: { type: 'coins', value: 1000 },
  },
  {
    id: 'coins_5000',
    name: 'Riche',
    description: 'Accumulez 5000 pièces',
    icon: '💎',
    rarity: 'epic',
    category: 'special',
    xpReward: 300,
    coinReward: 150,
    requirement: { type: 'coins', value: 5000 },
  },
  {
    id: 'coins_10000',
    name: 'Millionnaire',
    description: 'Accumulez 10000 pièces',
    icon: '👑',
    rarity: 'legendary',
    category: 'special',
    xpReward: 750,
    coinReward: 375,
    requirement: { type: 'coins', value: 10000 },
  },
  {
    id: 'streak_recovered',
    name: 'Revenant',
    description: 'Complétez une tâche après avoir perdu votre streak',
    icon: '💔',
    rarity: 'common',
    category: 'special',
    xpReward: 50,
    coinReward: 25,
    requirement: { type: 'streak_recovered', value: 1 },
    secret: true,
  },
  {
    id: 'first_subtask',
    name: 'Organisé',
    description: 'Créez votre première sous-tâche',
    icon: '📋',
    rarity: 'common',
    category: 'special',
    xpReward: 25,
    coinReward: 12,
    requirement: { type: 'subtasks_created', value: 1 },
  },
];

// Total: 100 achievements

export const RARITY_COLORS: Record<AchievementRarity, string> = {
  common: '#9ca3af',
  rare: '#3b82f6',
  epic: '#8b5cf6',
  legendary: '#f59e0b',
};

export const RARITY_LABELS: Record<AchievementRarity, string> = {
  common: 'Commun',
  rare: 'Rare',
  epic: 'Épique',
  legendary: 'Légendaire',
};

export const getAchievementById = (id: string): Omit<Achievement, 'unlockedAt'> | undefined => {
  return ACHIEVEMENTS.find(a => a.id === id);
};

export const getAchievementsByCategory = (category: string): Omit<Achievement, 'unlockedAt'>[] => {
  return ACHIEVEMENTS.filter(a => a.category === category);
};

export const getVisibleAchievements = (): Omit<Achievement, 'unlockedAt'>[] => {
  return ACHIEVEMENTS.filter(a => !a.secret);
};

export const getSecretAchievements = (): Omit<Achievement, 'unlockedAt'>[] => {
  return ACHIEVEMENTS.filter(a => a.secret);
};

export const getNonSecretAchievementCount = (): number => {
  return ACHIEVEMENTS.filter(a => !a.secret).length;
};
