// Configuration des achievements
import { Achievement, AchievementRarity } from '../types';

// Re-export for convenience
export type { AchievementRarity } from '../types';

export const ACHIEVEMENT_CATEGORIES = [
  { id: 'tasks', name: 'Tâches', icon: '📝' },
  { id: 'streaks', name: 'Séries', icon: '🔥' },
  { id: 'quests', name: 'Quêtes', icon: '🎯' },
  { id: 'level', name: 'Niveau', icon: '⭐' },
  { id: 'social', name: 'Social', icon: '👥' },
  { id: 'special', name: 'Spécial', icon: '🏆' },
];

export const ACHIEVEMENTS: Omit<Achievement, 'unlockedAt'>[] = [
  // ============ TASKS - Common ============
  {
    id: 'first_task',
    name: 'Premier Pas',
    description: 'Complétez votre première tâche',
    icon: '🎯',
    rarity: 'common',
    category: 'tasks',
    xpReward: 10,
    coinReward: 5,
    requirement: { type: 'tasks_completed', value: 1 },
  },
  {
    id: 'task_10',
    name: 'Débutant',
    description: 'Complétez 10 tâches',
    icon: '📝',
    rarity: 'common',
    category: 'tasks',
    xpReward: 25,
    coinReward: 10,
    requirement: { type: 'tasks_completed', value: 10 },
  },
  {
    id: 'task_50',
    name: 'Travailleur',
    description: 'Complétez 50 tâches',
    icon: '💼',
    rarity: 'rare',
    category: 'tasks',
    xpReward: 100,
    coinReward: 50,
    requirement: { type: 'tasks_completed', value: 50 },
  },
  {
    id: 'task_100',
    name: 'Productif',
    description: 'Complétez 100 tâches',
    icon: '🏆',
    rarity: 'rare',
    category: 'tasks',
    xpReward: 200,
    coinReward: 100,
    requirement: { type: 'tasks_completed', value: 100 },
  },
  {
    id: 'task_500',
    name: 'Machine de Guerre',
    description: 'Complétez 500 tâches',
    icon: '⚔️',
    rarity: 'epic',
    category: 'tasks',
    xpReward: 500,
    coinReward: 250,
    requirement: { type: 'tasks_completed', value: 500 },
  },
  {
    id: 'task_1000',
    name: 'Légende Vivante',
    description: 'Complétez 1000 tâches',
    icon: '👑',
    rarity: 'legendary',
    category: 'tasks',
    xpReward: 1000,
    coinReward: 500,
    requirement: { type: 'tasks_completed', value: 1000 },
  },

  // ============ STREAKS ============
  {
    id: 'streak_3',
    name: 'Régularité',
    description: 'Maintenez un streak de 3 jours',
    icon: '🔥',
    rarity: 'common',
    category: 'streaks',
    xpReward: 30,
    coinReward: 15,
    requirement: { type: 'streak', value: 3 },
  },
  {
    id: 'streak_7',
    name: 'Semaine Parfaite',
    description: 'Maintenez un streak de 7 jours',
    icon: '📅',
    rarity: 'common',
    category: 'streaks',
    xpReward: 75,
    coinReward: 35,
    requirement: { type: 'streak', value: 7 },
  },
  {
    id: 'streak_14',
    name: 'Persévérant',
    description: 'Maintenez un streak de 14 jours',
    icon: '💪',
    rarity: 'rare',
    category: 'streaks',
    xpReward: 150,
    coinReward: 75,
    requirement: { type: 'streak', value: 14 },
  },
  {
    id: 'streak_30',
    name: 'Mois Légendaire',
    description: 'Maintenez un streak de 30 jours',
    icon: '🌟',
    rarity: 'epic',
    category: 'streaks',
    xpReward: 300,
    coinReward: 150,
    requirement: { type: 'streak', value: 30 },
  },
  {
    id: 'streak_100',
    name: 'Centurion',
    description: 'Maintenez un streak de 100 jours',
    icon: '🏛️',
    rarity: 'legendary',
    category: 'streaks',
    xpReward: 1000,
    coinReward: 500,
    requirement: { type: 'streak', value: 100 },
  },
  {
    id: 'streak_365',
    name: 'Année Incroyable',
    description: 'Maintenez un streak de 365 jours',
    icon: '🎆',
    rarity: 'legendary',
    category: 'streaks',
    xpReward: 5000,
    coinReward: 2500,
    requirement: { type: 'streak', value: 365 },
    secret: true,
  },

  // ============ LEVELS ============
  {
    id: 'level_5',
    name: 'Apprenti',
    description: 'Atteignez le niveau 5',
    icon: '📈',
    rarity: 'common',
    category: 'xp',
    xpReward: 50,
    coinReward: 25,
    requirement: { type: 'level', value: 5 },
  },
  {
    id: 'level_10',
    name: 'Aventurier',
    description: 'Atteignez le niveau 10',
    icon: '🗺️',
    rarity: 'common',
    category: 'xp',
    xpReward: 100,
    coinReward: 50,
    requirement: { type: 'level', value: 10 },
  },
  {
    id: 'level_25',
    name: 'Héros',
    description: 'Atteignez le niveau 25',
    icon: '🦸',
    rarity: 'rare',
    category: 'xp',
    xpReward: 250,
    coinReward: 125,
    requirement: { type: 'level', value: 25 },
  },
  {
    id: 'level_50',
    name: 'Champion',
    description: 'Atteignez le niveau 50',
    icon: '🏅',
    rarity: 'epic',
    category: 'xp',
    xpReward: 500,
    coinReward: 250,
    requirement: { type: 'level', value: 50 },
  },
  {
    id: 'level_100',
    name: 'Maître Légendaire',
    description: 'Atteignez le niveau 100',
    icon: '👑',
    rarity: 'legendary',
    category: 'xp',
    xpReward: 2000,
    coinReward: 1000,
    requirement: { type: 'level', value: 100 },
  },

  // ============ XP MILESTONES ============
  {
    id: 'xp_1000',
    name: 'Collectionneur d\'XP',
    description: 'Gagnez 1000 XP au total',
    icon: '✨',
    rarity: 'common',
    category: 'xp',
    xpReward: 50,
    coinReward: 25,
    requirement: { type: 'total_xp', value: 1000 },
  },
  {
    id: 'xp_10000',
    name: 'Chasseur d\'XP',
    description: 'Gagnez 10000 XP au total',
    icon: '💫',
    rarity: 'rare',
    category: 'xp',
    xpReward: 200,
    coinReward: 100,
    requirement: { type: 'total_xp', value: 10000 },
  },
  {
    id: 'xp_100000',
    name: 'Maître de l\'XP',
    description: 'Gagnez 100000 XP au total',
    icon: '🌌',
    rarity: 'legendary',
    category: 'xp',
    xpReward: 1000,
    coinReward: 500,
    requirement: { type: 'total_xp', value: 100000 },
  },

  // ============ SPECIAL TASKS ============
  {
    id: 'first_epic',
    name: 'Premier Défi Épique',
    description: 'Complétez une tâche épique',
    icon: '💜',
    rarity: 'rare',
    category: 'tasks',
    xpReward: 100,
    coinReward: 50,
    requirement: { type: 'epic_tasks', value: 1 },
  },
  {
    id: 'first_legendary',
    name: 'Légende',
    description: 'Complétez une tâche légendaire',
    icon: '🌟',
    rarity: 'epic',
    category: 'tasks',
    xpReward: 250,
    coinReward: 125,
    requirement: { type: 'legendary_tasks', value: 1 },
  },
  {
    id: 'legendary_10',
    name: 'Chasseur de Légendes',
    description: 'Complétez 10 tâches légendaires',
    icon: '⭐',
    rarity: 'legendary',
    category: 'tasks',
    xpReward: 1000,
    coinReward: 500,
    requirement: { type: 'legendary_tasks', value: 10 },
  },

  // ============ TIME MANAGEMENT ============
  {
    id: 'early_bird',
    name: 'Lève-tôt',
    description: 'Complétez une tâche avant 7h du matin',
    icon: '🌅',
    rarity: 'common',
    category: 'time',
    xpReward: 25,
    coinReward: 10,
    requirement: { type: 'early_completion', value: 1 },
  },
  {
    id: 'night_owl',
    name: 'Oiseau de Nuit',
    description: 'Complétez une tâche après minuit',
    icon: '🦉',
    rarity: 'common',
    category: 'time',
    xpReward: 25,
    coinReward: 10,
    requirement: { type: 'late_completion', value: 1 },
  },
  {
    id: 'speed_demon',
    name: 'Éclair',
    description: 'Complétez 5 tâches en moins d\'une heure',
    icon: '⚡',
    rarity: 'rare',
    category: 'time',
    xpReward: 150,
    coinReward: 75,
    requirement: { type: 'fast_completion', value: 5 },
  },
  {
    id: 'perfect_day',
    name: 'Journée Parfaite',
    description: 'Complétez toutes vos tâches du jour',
    icon: '☀️',
    rarity: 'rare',
    category: 'time',
    xpReward: 100,
    coinReward: 50,
    requirement: { type: 'perfect_day', value: 1 },
  },
  {
    id: 'perfect_week',
    name: 'Semaine Parfaite',
    description: 'Complétez toutes vos tâches de la semaine',
    icon: '🌈',
    rarity: 'epic',
    category: 'time',
    xpReward: 500,
    coinReward: 250,
    requirement: { type: 'perfect_week', value: 1 },
  },

  // ============ CATEGORIES ============
  {
    id: 'category_master',
    name: 'Spécialiste',
    description: 'Complétez 50 tâches dans une même catégorie',
    icon: '🎓',
    rarity: 'rare',
    category: 'categories',
    xpReward: 150,
    coinReward: 75,
    requirement: { type: 'category_tasks', value: 50 },
  },
  {
    id: 'well_rounded',
    name: 'Polyvalent',
    description: 'Complétez des tâches dans toutes les catégories',
    icon: '🌐',
    rarity: 'rare',
    category: 'categories',
    xpReward: 200,
    coinReward: 100,
    requirement: { type: 'all_categories', value: 1 },
  },

  // ============ SPECIAL / SECRET ============
  {
    id: 'comeback',
    name: 'Le Retour',
    description: 'Reconnectez-vous après 7 jours d\'absence',
    icon: '🔄',
    rarity: 'common',
    category: 'special',
    xpReward: 50,
    coinReward: 25,
    requirement: { type: 'comeback', value: 7 },
    secret: true,
  },
  {
    id: 'perfectionist',
    name: 'Perfectionniste',
    description: 'Complétez 10 tâches avec toutes les sous-tâches',
    icon: '✅',
    rarity: 'rare',
    category: 'special',
    xpReward: 150,
    coinReward: 75,
    requirement: { type: 'perfect_tasks', value: 10 },
  },
  {
    id: 'overachiever',
    name: 'Surpassement',
    description: 'Gagnez 500 XP en une seule journée',
    icon: '🚀',
    rarity: 'epic',
    category: 'special',
    xpReward: 250,
    coinReward: 125,
    requirement: { type: 'daily_xp', value: 500 },
  },
  {
    id: 'founder',
    name: 'Fondateur',
    description: 'Créez votre compte',
    icon: '🏴',
    rarity: 'common',
    category: 'special',
    xpReward: 50,
    coinReward: 25,
    requirement: { type: 'account_created', value: 1 },
  },

  // ============ COLLECTION ============
  {
    id: 'collector_10',
    name: 'Petit Collectionneur',
    description: 'Débloquez 10 achievements',
    icon: '📦',
    rarity: 'common',
    category: 'collection',
    xpReward: 100,
    coinReward: 50,
    requirement: { type: 'achievements', value: 10 },
  },
  {
    id: 'collector_25',
    name: 'Grand Collectionneur',
    description: 'Débloquez 25 achievements',
    icon: '🗃️',
    rarity: 'rare',
    category: 'collection',
    xpReward: 300,
    coinReward: 150,
    requirement: { type: 'achievements', value: 25 },
  },
  {
    id: 'collector_all',
    name: 'Collectionneur Ultime',
    description: 'Débloquez tous les achievements',
    icon: '🏆',
    rarity: 'legendary',
    category: 'collection',
    xpReward: 2000,
    coinReward: 1000,
    requirement: { type: 'achievements', value: 999 },
    secret: true,
  },

  // ============ QUESTS ============
  {
    id: 'quest_first',
    name: 'Quêteur',
    description: 'Complétez votre première quête',
    icon: '📜',
    rarity: 'common',
    category: 'special',
    xpReward: 50,
    coinReward: 25,
    requirement: { type: 'quests_completed', value: 1 },
  },
  {
    id: 'quest_10',
    name: 'Aventurier Confirmé',
    description: 'Complétez 10 quêtes',
    icon: '🗡️',
    rarity: 'rare',
    category: 'special',
    xpReward: 200,
    coinReward: 100,
    requirement: { type: 'quests_completed', value: 10 },
  },
  {
    id: 'daily_warrior',
    name: 'Guerrier Quotidien',
    description: 'Complétez 30 quêtes journalières',
    icon: '⚔️',
    rarity: 'epic',
    category: 'special',
    xpReward: 500,
    coinReward: 250,
    requirement: { type: 'daily_quests', value: 30 },
  },
];

export const RARITY_COLORS: Record<AchievementRarity, string> = {
  common: '#9ca3af',
  rare: '#3b82f6',
  epic: '#8b5cf6',
  legendary: '#f59e0b',
};

export const RARITY_LABELS: Record<AchievementRarity, string> = {
  common: 'Commun',
  rare: 'Rare',
  epic: 'Épique',
  legendary: 'Légendaire',
};

export const getAchievementById = (id: string): Omit<Achievement, 'unlockedAt'> | undefined => {
  return ACHIEVEMENTS.find(a => a.id === id);
};

export const getAchievementsByCategory = (category: string): Omit<Achievement, 'unlockedAt'>[] => {
  return ACHIEVEMENTS.filter(a => a.category === category);
};

export const getVisibleAchievements = (): Omit<Achievement, 'unlockedAt'>[] => {
  return ACHIEVEMENTS.filter(a => !a.secret);
};
